---
sudo: required
dist: trusty
language: python
services:
  - docker
before_script:
  - pip install ansible==$ANSIBLE_VERSION
  - pip install molecule
  - pip install docker-py
script:
  - molecule test
matrix:
  include:
    - env: ANSIBLE_VERSION="2.3.3"
    - env: ANSIBLE_VERSION="2.4.4"
    - env: ANSIBLE_VERSION="2.5.2"
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
