---
- name: RedHat - Install IDO Module and Dependencies
  become: yes
  yum:
    name:
      - mariadb-server
      - icinga2-ido-mysql
    state: present
  when: i2_manage_package
  tags:
    - install

- name: RedHat - Make sure MariaDB is started
  service:
    name: mariadb
    state: started
    enabled: yes
  when: i2_manage_service
