---
- name: include icinga2.yml
  include: icinga2.yml
  tags:
      - install

- name: Make sure Icinga 2 is started
  service:
      name: icinga2
      state: started
      enabled: yes
  when: i2_manage_service
