---
- name: Include OS specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
    - feature-handler
    - config

- name: include icinga2.yml
  include: icinga2.yml
  tags:
    - install

- name: include icinga2-config.yml
  include: icinga2-config.yml
  tags:
    - config

- name: include icinga2-features.yml
  include_tasks: icinga2-features.yml
  when: i2_features|flatten|length > 0
  tags:
    - feature-handler

- name: Make sure Icinga 2 is started
  service:
    name: icinga2
    state: started
    enabled: yes
  when: i2_manage_service
