---
- name: start icinga2
  become: yes
  service:
    name: icinga2
    state: started
    enabled: yes
  when: i2_manage_service

- name: reload icinga2
  become: yes
  service:
    name: icinga2
    state: reloaded
  when: i2_manage_service
